import { ImageResponse } from 'next/og';
import { readFile } from 'node:fs/promises';
import path from 'node:path';

export const size = { width: 1200, height: 630 };
export const contentType = 'image/png';
export const alt = 'bines.ai — editorial notes on AI and life';

/**
 * Site-wide OpenGraph image. Mirrors the site header: b-stamp colophon
 * (curved Kentucky · London text preserved via a pre-rasterised PNG) on
 * the left, "bines.ai" wordmark with ruby dot on the right. No bio line —
 * the og:description shown beneath the card by every chat client supplies
 * the same text already, so repeating it inside the image just duplicates.
 *
 * The stamp PNG is generated by cairosvg, NOT rsvg-convert — rsvg-convert
 * silently drops <textPath> elements. Regenerate with:
 *
 *   sed 's/currentColor/#1A1814/g' public/stamp.svg > /tmp/stamp-ink.svg
 *   cairosvg /tmp/stamp-ink.svg -o public/media/og-stamp.png --output-width 720
 *
 * Per-Fieldwork pieces have their own OG image at
 * src/app/fieldwork/[slug]/opengraph-image.tsx.
 */
export default async function Image() {
  const PAPER = '#FFFFF4';
  const INK = '#1A1814';
  const RUBY = '#B0213A';

  const stampPath = path.join(process.cwd(), 'public', 'media', 'og-stamp.png');
  const stampBytes = await readFile(stampPath);
  const stampSrc = `data:image/png;base64,${stampBytes.toString('base64')}`;

  return new ImageResponse(
    (
      <div
        style={{
          width: '100%',
          height: '100%',
          background: PAPER,
          color: INK,
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          gap: 56,
          padding: 120,
          fontFamily: 'serif',
        }}
      >
        <img src={stampSrc} width={220} height={220} alt="" style={{ flexShrink: 0 }} />

        <div
          style={{
            fontSize: 140,
            fontWeight: 900,
            letterSpacing: -4,
            lineHeight: 1,
            display: 'flex',
            alignItems: 'baseline',
          }}
        >
          <span>bines</span>
          <span style={{ color: RUBY }}>.</span>
          <span>ai</span>
        </div>
      </div>
    ),
    { ...size },
  );
}
